TestMVC/Controllers/InfoMedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestMVC.Domain.ViewModels;
using TestMVC.Provider;
using TestMVC.Core;
using TestMVC.Data.Contexts;
using System.Threading.Tasks;
using System.Text.RegularExpressions;

namespace TestMVC.Controllers
{
    public class InfoMedicineController : Controller
    {
        protected List<InfoAndCategoryViewModel> InfoMedicineList
        {
            get
            {
                if (Session["InfoMedicineList"] == null)
                { return null; }
                else
                { return Session["InfoMedicineList"] as List<InfoAndCategoryViewModel>; }
            }
            set { Session["InfoMedicineList"] = value; }
        }
        protected List<ShoppingCartViewModel> ShoppingList
        {
            get
            {
                if (Session["ShoppingList"] == null)
                { return null; }
                else
                { return Session["ShoppingList"] as List<ShoppingCartViewModel>; }
            }
            set { Session["ShoppingList"] = value; }
        }
        private readonly IMedicineUsageProvider _medicineusageprovider;
        private readonly IInfoMedicineProvider _infoMedicineProvider;
        private readonly IMedicineCategoryProvider _medicineCategoryProvider;
        private readonly IInfoAndCategoryProvider _infoAndCategoryProvider;
        private readonly IShoppingCartProvider _shoppingCartProvider;
        private readonly IMedicineOrderProvider _medicineOrderProvider;
        public InfoMedicineController(IMedicineUsageProvider medicineusageprovider, IInfoMedicineProvider infoMedicineProvider, IMedicineCategoryProvider medicineCategoryProvider,
            IInfoAndCategoryProvider infoAndCategoryProvider, IShoppingCartProvider shoppingCartProvider, IMedicineOrderProvider medicineOrderProvider)
        {
            _medicineusageprovider = medicineusageprovider;
            _infoMedicineProvider = infoMedicineProvider;
            _medicineCategoryProvider = medicineCategoryProvider;
            _infoAndCategoryProvider = infoAndCategoryProvider;
            _shoppingCartProvider = shoppingCartProvider;
            _medicineOrderProvider = medicineOrderProvider;
        }
        public ActionResult Main()
        {
            Session["status"] = "Medicine Information";
            if (Session["LoginUserName"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                var viewModel = new InfoAndCategoryViewModel();
                viewModel.Usage = GetUsageListItemAsync();
                Search();
                return View(viewModel);
            }

        }
        public ActionResult Add()
        {
            //var viewModel = new InfoMedicineAdd();
            //viewModel.Usage = GetUsageListItemAsync();
            //return View(viewModel);
            Session["status"] = "Add Medicine Information";
            if (Session["LoginUserName"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            MedicineInfoAndCategoryViewModel model = new MedicineInfoAndCategoryViewModel();
            string Medicineno = Request.Form.Get("ID");
            model.Usage = GetUsageListItemAsync();
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Add(string Medicineno)
        {
            Medicineno = Request.Form.Get("ID");
            var IdExist = await _infoMedicineProvider.GetInfoMedicineByIdAsync(Medicineno);
            if (IdExist != null)
            {
                return Content("<script>alert('This Medicine Number has been already added!');history.go(-1);</script>");
            }
            else
            {
                string ID = Medicineno;
                string name = Request.Form.Get("name");
                string origin = Request.Form.Get("origin");
                string PD = Request.Form.Get("PD");
                if (Convert.ToDateTime(PD) > DateTime.Now.AddDays(-1))
                {
                    return Content("<script>alert('Production date must be smaller than or equal to today.');history.go(-1);</script>");
                }
                string EXP = Request.Form.Get("EXP") + Request.Form.Get("date");
                string price = Request.Form.Get("price");
                string category = Request.Form.Get("category");
                string usage = Request.Form.Get("Usage");
                _infoMedicineProvider.EditInfoMedicine(ID, name, origin, PD, EXP, price);
                _medicineCategoryProvider.EditCategory(ID, category, usage);
                return Content("<script>alert('Add Success!');window.location.href='Main';</script>");
            }
        }
        protected List<SelectListItem> GetUsageListItemAsync()
        {
            List<SelectListItem> listItem = new List<SelectListItem>();
            List<MedicineUsageViewModel> list = _medicineusageprovider.GetMedicineUsage();
            if (list != null && list.Count > 0)
            {
                for (int i = 0; i < list.Count; i++)
                {
                    SelectListItem item = new SelectListItem();
                    item.Text = list[i].usage.ToString();
                    item.Value = list[i].usage.ToString();
                    listItem.Add(item);
                }
            }
            return listItem;
        }

        [HttpPost]
        public ActionResult Search()
        {
            var Model = new List<InfoAndCategoryViewModel>();
            List<InfoAndCategoryViewModel> Infolist = new List<InfoAndCategoryViewModel>();
            string Id = null;
            string Category = null;
            string Usage = null;
            InfoMedicineContext dbMedicine = new InfoMedicineContext();
            MedicineCategoryContext dbCategory = new MedicineCategoryContext();
            if (Request.Form.Count > 0)
            {
                if ((Request.Form.Get("ID")) != "default")
                {
                    Id = Request.Form.Get("ID").ToString();
                }
                if ((Request.Form.Get("category")) != "default")
                {
                    Category = Request.Form.Get("category").ToString();
                }
                if ((Request.Form.Get("usage")) != "default")
                {
                    Usage = Request.Form.Get("usage").ToString();
                }
            }
            else
            {
                if (Session["ID"] != null)
                    Id = Session["ID"].ToString();
                if (Session["category"] != null)
                    Category = Session["category"].ToString();
                if (Session["usage"] != null)
                    Usage = Session["usage"].ToString();
            }
            if (Id == "")
                Id = null;
            if (Category == "--select--")
                Category = null;

            if (Id == null && Category == null && Usage == null)
            {
                Infolist = _infoAndCategoryProvider.GetInfoAndCategory();
                for (int i = 0; i < Infolist.Count; i++)
                {
                    InfoAndCategoryViewModel List = new InfoAndCategoryViewModel();
                    List.ID = Infolist[i].ID;
                    List.name = Infolist[i].name;
                    List.origin = Infolist[i].origin;
                    List.PD = Infolist[i].PD;
                    List.EXP = Infolist[i].EXP;
                    List.price = Infolist[i].price;
                    List.category = Infolist[i].category;
                    List.usage = Infolist[i].usage;
                    Model.Add(List);
                }
                ViewBag.length = Infolist.Count;
                System.Web.HttpContext.Current.Session["Category"] = null;
                System.Web.HttpContext.Current.Session["Usage"] = null;
            }
            else if (Id == null && Category == null && Usage != null)
            {
                Infolist = _infoAndCategoryProvider.GetInfoAndCategoryByUsage(Usage);
                for (int i = 0; i < Infolist.Count; i++)
                {
                    InfoAndCategoryViewModel List = new InfoAndCategoryViewModel();
                    List.ID = Infolist[i].ID;
                    List.name = Infolist[i].name;
                    List.origin = Infolist[i].origin;
                    List.PD = Infolist[i].PD;
                    List.EXP = Infolist[i].EXP;
                    List.price = Infolist[i].price;
                    List.category = Infolist[i].category;
                    List.usage = Infolist[i].usage;
                    Model.Add(List);
                }
                ViewBag.length = Infolist.Count;
                System.Web.HttpContext.Current.Session["Category"] = null;
                System.Web.HttpContext.Current.Session["Usage"] = Usage;
            }
            else if (Id == null && Category != null && Usage == null)
            {
                Infolist = _infoAndCategoryProvider.GetInfoAndCategoryByCategory(Category);
                for (int i = 0; i < Infolist.Count; i++)
                {
                    InfoAndCategoryViewModel List = new InfoAndCategoryViewModel();
                    List.ID = Infolist[i].ID;
                    List.name = Infolist[i].name;
                    List.origin = Infolist[i].origin;
                    List.PD = Infolist[i].PD;
                    List.EXP = Infolist[i].EXP;
                    List.price = Infolist[i].price;
                    List.category = Infolist[i].category;
                    List.usage = Infolist[i].usage;
                    Model.Add(List);
                }
                System.Web.HttpContext.Current.Session["Category"] = Category;
                System.Web.HttpContext.Current.Session["Usage"] = null;

TestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Css/bootstrap.min3.3.7.css" rel="stylesheet" />
    <script src="~/js/popper.js"></script>
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <style>
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 30px;
            background-color: darkgray;
        }
    </style>
</head>
<body>
    @{ string loginUserDisplayName = Session["LoginUserName"] == null ? string.Empty : Session["LoginUserName"].ToString();}
    @{ string Year = Session["Year"] == null ? string.Empty : Session["Year"].ToString();}
    @{ string Status = Session["status"] == null ? string.Empty : Session["status"].ToString();}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div>
            <div class="navbar-header">
                <span><a class="navbar-brand" style="color:white">Medicine Shop</a></span>
            </div>
        </div>
        <div class="dropdown pull-right">
            <a class="btn btn-lg btn-inverse dropdown-toggle pull-right" role="button" data-toggle="dropdown" style="color: white">
                <span class="glyphicon glyphicon-user"></span>Hi,@loginUserDisplayName!
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                <li><a class="btn" href="@Url.Action("Edit","Account")" role="menuitem">PersonalInfo</a></li>
                <li><a class="btn" href="@Url.Action("Modify","Account")" role="menuitem">Modify password</a></li>
                <li>
                    <a class="btn" role="menuitem" href="@Url.Action("ShoppingCart","InfoMedicine")">
                        <span class="glyphicon glyphicon-shopping-cart"></span>Shopping
                    </a>
                </li>
                <li><a class="btn" href="@Url.Action("Order","InfoMedicine")" role="menuitem">Order</a></li>
                <li><a class="btn" href="@Url.Action("Login","Account")" role="menuitem">Quit</a></li>
            </ul>
        </div>
    </nav>
    <div style="margin-top: 100px;height: 50px">
        <ul style="list-style: none; margin-left: -20px">
            <li>
                <h3><label>@Status</label></h3>
            </li>
        </ul>
    </div>
    <hr style="width: 100%" />
    <div class="container" style="min-width:800px">
        @RenderBody()
    </div>
    <footer class="footer" style="text-align:center">
        <p style="margin-top:5px">&copy;2017--@Year Medicine</p>
    </footer>
</body>
</html>

TestMVC/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Css/bootstrap.min3.3.7.css" rel="stylesheet" />
    <script src="~/js/popper.js"></script>
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <style>
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 30px;
            background-color: darkgray;
        }
    </style>
</head>
<body>
    @{ string loginUserDisplayName = Session["LoginUserName"] == null ? string.Empty : Session["LoginUserName"].ToString();}
    @{ string Year = Session["Year"] == null ? string.Empty : Session["Year"].ToString();}
    @{ string Status = Session["status"] == null ? string.Empty : Session["status"].ToString();}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div>
            <div class="navbar-header">
                <span><a class="navbar-brand" style="color:white">Medicine Manager</a></span>
            </div>
        </div>
        <div class="dropdown pull-right">
            <a class="btn btn-lg btn-inverse dropdown-toggle pull-right" role="button" data-toggle="dropdown" style="color: white">
                Hi,@loginUserDisplayName!
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                <li><a class="btn" href="@Url.Action("Edit","Account")" role="menuitem">PersonalInfo</a></li>
                <li><a class="btn" href="@Url.Action("Modify","Account")" role="menuitem">Modify password</a></li>
                <li><a class="btn" href="@Url.Action("Login","Account")" role="menuitem">Quit</a></li>
            </ul>
        </div>
    </nav>
    <div style="margin-top: 100px;height: 50px">
    <ul style="list-style: none; margin-left: -20px">
        <li>
            <h3><label>@Status</label></h3>
        </li>
    </ul>
    </div>
    <hr style="width: 100%" />
    <div class="container">
        @RenderBody()
    </div>

    <footer class="footer" style="text-align:center">
        <p style="margin-top:5px">&copy;2017--@Year Medicine Manager</p>
    </footer>
</body>
</html>